setup.py
=> Commented out line-profiler

fc/parsing/CompactSyntaxParser.py, fc/protocol.py, test/TestCompactSyntaxParser.py
=> Remove xml output code from CompactSyntaxParser

fc/environment.py, fc/parsing/CompactSyntaxParser.py, test/test_CompactSyntaxParser.py, test/test_array_expressions.py, test/test_syntax_interface.py
=> Further refactoring for PEP8 names.

fc/data_loading.py, fc/language/values.py, fc/test_support.py
=> Moved data loading methods into own module, outside of test_support.

fc/code_generation.py, fc/parsing/actions.py, fc/protocol.py, fc/templates/weblab_model.pyx, requirements/cellmlmanip.sh
This PR contains enough to get the GraphState protocol working again without units conversions.
It also updates a few things to the latest cellmlmanip.
=> Migrate ModelInterface functionality to parse actions

fc/protocol.py, test/models/difrancesco_noble_model_1985.cellml, test/models/paci_hyttinen_aaltosetala_severi_atrialVersion.cellml, test/models/paci_hyttinen_aaltosetala_severi_ventricularVersion.cellml, test/test_generated_model_graphstate.py
Part of #22. Implements unit conversion for time, checked with the GraphState protocol.
=> Time unit conversion

fc/plotting.py, fc/protocol.py
=> Move plotting code out of Protocol class.

fc/code_generation.py, fc/parsing/actions.py, fc/parsing/rdf.py, fc/protocol.py, fc/templates/weblab_model.pyx, test/test_code_generation.py
=> Refactor model manipulation

CONTRIBUTING.md
with some links I find useful
in particular I had no idea where isort's ordering rules were defined
=> Initial CONTRIBUTING.md file

fc/parsing/actions.py, test/models/luo_rudy_1991.cellml, test/test_sim_environments.py
Part of #95, but I suspect it would be worth merging in this state since it documents where other parts of #23 might need to make changes! Then actually implementing #95 could be a separate PR.
=> Preparatory work and documentation

fc/code_generation.py, fc/parsing/actions.py, test/test_code_generation.py
https://github.com/ModellingWebLab/cellmlmanip/pull/229
=> Updated code to work with recent cellmlmanip changes.

README.md, fc/code_generation.py, fc/parsing/actions.py, fc/parsing/rdf.py, test/test_code_generation.py
See https://github.com/ModellingWebLab/cellmlmanip/pull/237
=> Adapted code for recent cellmlmanip changes.

.gitignore, CONTRIBUTING.md, setup.py
=> Added pytest-profiling dependency.

fc/code_generation.py, test/test_weblab_printer.py
https://github.com/ModellingWebLab/cellmlmanip/pull/251
=> Fix for recent changes in cellmlmanip

.gitignore, fc/parsing/CompactSyntaxParser.py
=> Caching protocol files in memory and on disk.

fc/parsing/actions.py
Should give us a small performance boost - see #112.
=> We don't need numbers to purge mathematics

fc/parsing/actions.py, test/test_sim_environments.py
=> Added test for mem-caching of protocols leading to shared ModelInterface state.

test/data/simple_ode.cellml, test/protocols/test_unit_conversion_inputs.txt, test/protocols/test_unit_conversion_inputs_defines.txt, test/protocols/test_unit_conversion_inputs_initial_values.txt, test/test_unit_conversion_inputs.py
=> Tests for unit conversion

fc/parsing/actions.py, test/test_unit_conversion_inputs.py
Seems to work for the initial value version
For the define version there's an issue with initial values not being available, not sure why
=> Added unit conversion for inputs.

fc/code_generation.py, fc/parsing/actions.py, fc/protocol.py, fc/templates/weblab_model.pyx, test/code_generation/weblab_model.pyx, test/test_code_generation.py, test/test_mathml_evaluation.py, test/test_various_protocols.py
Fixes #97 
Seems to pass now, but doesn't have trig functions and raises 2 warnings
=> Mathml evaluation

fc/parsing/actions.py, test/test_clamping.py, test/test_environment.py, test/test_nested_protocols.py, test/test_other_ontologies.py, test/test_while_loop.py
=> Support units_of()

fc/parsing/actions.py, test/protocols/test_var_declaration.txt, test/protocols/test_var_declaration_overdefined.txt, test/protocols/test_var_declaration_redefined.txt, test/protocols/test_var_declaration_underdefined.txt, test/test_var_declarations.py
=> Add support for var declarations.

.travis.yml, fc/parsing/actions.py, fc/protocol.py, test/test_imported_protocols.py, test/test_nested_protocols.py
Will fix #106 by addressing the units conversion aspect.
Also fixes #107.
Requires https://github.com/ModellingWebLab/cellmlmanip/pull/265; `.travis.yml` will need changing back once that is merged.
=> Add unit conversion for new/changed equations

fc/parsing/CompactSyntaxParser.py
Not sure how this one snuck in, but pretty sure it should be a simple expression given the context! I doubt it'll break anything changing it :)
=> Resolve an oddity

fc/code_generation.py, fc/parsing/CompactSyntaxParser.py, fc/parsing/actions.py, fc/parsing/rdf.py, test/models/unit_conversion_rules.cellml, test/protocols/test_unit_conversion_rules.txt, test/test_unit_conversion_rules.py
=> Unit conversion rules

fc/parsing/CompactSyntaxParser.py, fc/parsing/actions.py, fc/protocol.py, test/protocols/test_INa_IV_curves.txt, test/test_iv_curves.py
=> Run INa IV protocols

fc/code_generation.py
Needed to make FC work with latest cellmlmanip
=> Updated reference to cellmlmanip transpiler.

test/protocols/test_unit_conversion_time_conflict.txt, test/protocols/test_unit_conversion_time_duplicate.txt, test/protocols/test_unit_conversion_time_independent_var_units.txt, test/protocols/test_unit_conversion_time_input.txt, test/test_unit_conversion.py
=> More tests for time unit conversion

fc/environment.py, fc/error_handling.py, fc/file_handling.py, fc/locatable.py, fc/parsing/CompactSyntaxParser.py, fc/parsing/actions.py, fc/protocol.py, fc/simulations/__init__.py, fc/simulations/model.py, fc/simulations/modifiers.py, fc/simulations/ranges.py, fc/simulations/simulations.py, fc/simulations/solvers.py, fc/test_support.py
=> Updated docstrings. 

fc/parsing/actions.py, fc/protocol.py, test/test_empty_sections.py
=> Test and deal with empty sections
